Det 143 py test to check python files
KYD-Analytics/gh-actions-data-qa-tools pull request #2
Opened 2023-04-26 15:27 UTC by Kwill3

2023-04-27 08:44 UTC, GarethIsaac commented on src/version_overlap_check.py
> +    return overlap_list
You are returning a list, but in the header it says you are returning a int.

2023-04-27 08:45 UTC, GarethIsaac requested changes
Please correct the name of the test scenarios and update the information

2023-04-27 11:05 UTC, Kwill3 commented on src/version_overlap_check.py
> +    return overlap_list
Resolved, now returning a tuple of count and list.

2023-04-27 11:06 UTC, Kwill3 commented on src/test_version_overlap_check.py
> +    assert count == {}
Resolved, now named as output and checking for a tuple [int, dict]

2023-04-27 11:07 UTC, Kwill3 commented
Descriptions and comments now updated. Return types and tests are also corrected.

2023-04-28 08:59 UTC, GarethIsaac approved these changes

2023-04-28 09:01 UTC, merged